# Tomado de: https://hub.docker.com/_/ghost/
# Secci√≥n: Production mode ... via docker stack deploy or docker-compose
version: "3.1"

name: pruebas-ghost

services:
  ghost:
    container_name: ghost
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: X02kt6Nr014E74I24Sx8
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      # - ./volumes/ghost:/var/lib/ghost/content
      - ghost:/var/lib/ghost/content

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: X02kt6Nr014E74I24Sx8
    volumes:
      # - ./volumes/db:/var/lib/mysql
      db:/var/lib/mysql

volumes:
  ghost:
  db: